CREATE TABLE TEST_ENTITY (
    ID INTEGER  PRIMARY KEY,
    NAME VARCHAR(225) NOT NULL,
    EMP_NO VARCHAR (225)
);
-- INSERT INTO MEMBER_ENTITY (ID, EMP_NO, NAME) VALUES (9, MEMBER_ENTITY 'NO_1', 'Matt');